import { Task, Project } from '@/types';

export const seedProjects = [
  {
    id: 'project-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website',
    color: '#3b82f6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project-2',
    name: 'Mobile App',
    description: 'Native mobile application development',
    color: '#10b981',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project-3',
    name: 'Marketing Campaign',
    description: 'Q4 marketing initiative',
    color: '#f59e0b',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project-4',
    name: 'Internal Tools',
    description: 'Productivity and automation tools',
    color: '#8b5cf6',
    createdAt: new Date().toISOString(),
  },
];

export const seedTasks = [
  {
    id: 'task-1',
    title: 'Design homepage mockup',
    description: 'Create wireframes and high-fidelity mockups for the new homepage',
    priority: 'High',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['design', 'ui'],
    projectId: 'project-1',
    estimatedTime: 4,
    assignee: 'John Doe',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-2',
    title: 'Implement user authentication',
    description: 'Set up JWT-based authentication system',
    priority: 'Urgent',
    status: 'Todo',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['backend', 'security'],
    projectId: 'project-2',
    estimatedTime: 8,
    assignee: 'Jane Smith',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-3',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints',
    priority: 'Medium',
    status: 'Review',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['documentation'],
    projectId: 'project-1',
    estimatedTime: 3,
    assignee: 'Bob Wilson',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-4',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    priority: 'High',
    status: 'Completed',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['devops'],
    projectId: 'project-4',
    estimatedTime: 6,
    assignee: 'Alice Johnson',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    archived: false,
  },
  {
    id: 'task-5',
    title: 'Create social media content',
    description: 'Design and write content for social media campaign',
    priority: 'Medium',
    status: 'Todo',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['marketing', 'content'],
    projectId: 'project-3',
    estimatedTime: 5,
    assignee: 'Carol Davis',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-6',
    title: 'Optimize database queries',
    description: 'Improve performance of slow database queries',
    priority: 'Urgent',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['backend', 'performance'],
    projectId: 'project-2',
    estimatedTime: 10,
    assignee: 'John Doe',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-7',
    title: 'Conduct user research',
    description: 'Interview users and gather feedback',
    priority: 'Medium',
    status: 'Todo',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['research', 'ux'],
    projectId: 'project-1',
    estimatedTime: 8,
    assignee: 'Jane Smith',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-8',
    title: 'Build analytics dashboard',
    description: 'Create dashboard for tracking key metrics',
    priority: 'High',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['frontend', 'analytics'],
    projectId: 'project-4',
    estimatedTime: 12,
    assignee: 'Bob Wilson',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-9',
    title: 'Email campaign setup',
    description: 'Configure email marketing automation',
    priority: 'Low',
    status: 'Todo',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['marketing', 'automation'],
    projectId: 'project-3',
    estimatedTime: 4,
    assignee: 'Carol Davis',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-10',
    title: 'Mobile app testing',
    description: 'Perform QA testing on iOS and Android',
    priority: 'High',
    status: 'Review',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['testing', 'mobile'],
    projectId: 'project-2',
    estimatedTime: 6,
    assignee: 'Alice Johnson',
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-11',
    title: 'Implement dark mode',
    description: 'Add dark mode support to the application',
    priority: 'Low',
    status: 'Completed',
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['frontend', 'ui'],
    projectId: 'project-1',
    estimatedTime: 3,
    assignee: 'John Doe',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    archived: false,
  },
  {
    id: 'task-12',
    title: 'Security audit',
    description: 'Perform comprehensive security review',
    priority: 'Urgent',
    status: 'Todo',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['security', 'audit'],
    projectId: 'project-4',
    estimatedTime: 16,
    assignee: 'Jane Smith',
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-13',
    title: 'Create landing page',
    description: 'Design and develop marketing landing page',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['design', 'frontend'],
    projectId: 'project-3',
    estimatedTime: 8,
    assignee: 'Bob Wilson',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-14',
    title: 'Set up monitoring',
    description: 'Configure application monitoring and alerting',
    priority: 'High',
    status: 'Todo',
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['devops', 'monitoring'],
    projectId: 'project-4',
    estimatedTime: 5,
    assignee: 'Alice Johnson',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-15',
    title: 'Write unit tests',
    description: 'Increase test coverage to 80%',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['testing', 'quality'],
    projectId: 'project-2',
    estimatedTime: 15,
    assignee: 'Carol Davis',
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-16',
    title: 'Design system documentation',
    description: 'Document design tokens and components',
    priority: 'Low',
    status: 'Todo',
    dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['design', 'documentation'],
    projectId: 'project-1',
    estimatedTime: 6,
    assignee: 'John Doe',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-17',
    title: 'Performance optimization',
    description: 'Optimize bundle size and load times',
    priority: 'High',
    status: 'Review',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['frontend', 'performance'],
    projectId: 'project-1',
    estimatedTime: 7,
    assignee: 'Jane Smith',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-18',
    title: 'Backup strategy',
    description: 'Implement automated backup system',
    priority: 'Medium',
    status: 'Completed',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['devops', 'security'],
    projectId: 'project-4',
    estimatedTime: 4,
    assignee: 'Bob Wilson',
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    archived: false,
  },
  {
    id: 'task-19',
    title: 'User onboarding flow',
    description: 'Design and implement onboarding experience',
    priority: 'Medium',
    status: 'Todo',
    dueDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['ux', 'frontend'],
    projectId: 'project-2',
    estimatedTime: 9,
    assignee: 'Alice Johnson',
    createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
  {
    id: 'task-20',
    title: 'A/B testing setup',
    description: 'Configure A/B testing framework',
    priority: 'Low',
    status: 'Todo',
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['analytics', 'marketing'],
    projectId: 'project-3',
    estimatedTime: 7,
    assignee: 'Carol Davis',
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    archived: false,
  },
];

export function initializeSeedData() {
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('task-manager-storage');
    if (!stored) {
      return { tasks: seedTasks, projects: seedProjects };
    }
  }
  return null;
}
